<?php

/**
 * @file
 * Implements theme relatet functions.
 */

/**
 * Implements hook_preprocess_menu_local_task().
 */
function woldtwerk_bootstrap_v5_preprocess_menu_local_task(&$variables) {
  $active = $variables["is_active"] ?? FALSE;

  $variables['link']['#options']['attributes']['class'][] = 'nav-link';
  if ($active) {
    $variables['link']['#options']['attributes']['class'][] = 'active';
  }
}
